# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/graphics/php56-gd/Makefile 402669 2015-11-30 14:05:47Z ale $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-gd

.include "${MASTERDIR}/Makefile"
