# Created by: Martin Matuska <mm@FreeBSD.org>
# $FreeBSD: head/www/php56-opcache/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-opcache

USE_ZENDEXT=	yes

.include "${MASTERDIR}/Makefile"
