# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/www/php56-tidy/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-tidy

.include "${MASTERDIR}/Makefile"
