# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/devel/php56-tokenizer/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-tokenizer

.include "${MASTERDIR}/Makefile"
