# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/graphics/php56-exif/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-exif

.include "${MASTERDIR}/Makefile"
