# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/devel/php56-gettext/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-gettext

.include "${MASTERDIR}/Makefile"
