# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/converters/php56-mbstring/Makefile 403795 2015-12-15 17:13:56Z ale $

CATEGORIES=	converters

MASTERDIR=	${.CURDIR}/../../lang/php70

PKGNAMESUFFIX=	-mbstring

.include "${MASTERDIR}/Makefile"
