# Created by: Alex Dupre <ale@FreeBSD.org>
# $FreeBSD: head/devel/php56-shmop/Makefile 367268 2014-09-04 14:24:25Z ale $

CATEGORIES=	devel

MASTERDIR=	${.CURDIR}/../../lang/php7

PKGNAMESUFFIX=	-shmop

.include "${MASTERDIR}/Makefile"
